version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: "app"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:54322/postgres
      - DIRECT_URL=postgresql://postgres:postgres@host.docker.internal:54322/postgres
    volumes:
      - .:/app
      - /app/.next
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    stdin_open: true
